// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ray.EntityFrameworkRepository;

namespace RayPI.EntityFrameworkRepository.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20190815091852_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RayPI.Entity.BookEntity", b =>
                {
                    b.Property<long>("Id");

                    b.Property<long?>("CreateId");

                    b.Property<string>("CreateName")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<DateTime?>("DeleteTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long?>("UpdateId");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("Writer");

                    b.HasKey("Id");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("RayPI.Entity.StudentEntity", b =>
                {
                    b.Property<long>("Id");

                    b.Property<long>("ClassId");

                    b.Property<long?>("CreateId");

                    b.Property<string>("CreateName")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<DateTime?>("DeleteTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long?>("UpdateId");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdateTime");

                    b.HasKey("Id");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("RayPI.Entity.Teacher", b =>
                {
                    b.Property<long>("Id");

                    b.Property<long?>("CreateId");

                    b.Property<string>("CreateName")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<DateTime?>("DeleteTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long?>("UpdateId");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("UpdateTime");

                    b.HasKey("Id");

                    b.ToTable("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
